### ISSUE TITLE
Festival crashes when trying to scan my music library

### ISSUE THREAD

**Issue by moritz1000** [hinto-janai/festival#26]
## OS & Version
Festival v1.0.0
shukusai v0.0.1
Linux x64
894a5f1b8dfa14b8b73157511c0d4baab6d06063

## Bug
Festival crashes when I try to scan my music library. 
The error must be caused by a specifig song(s) in my library because when I e.g. only add a single folder to my collection `Music/test_festival/` (containing only one song) and then scan - it does work.

Unsure how to figure out what song(s) is causing Festival to crash.

## Steps
1. Click on:
![image](https://github.com/hinto-janai/festival/assets/35174351/5e2b408f-72f0-4780-b17b-ae62685d2745)
2. Observe:
![image](https://github.com/hinto-janai/festival/assets/35174351/45502e38-7580-45d2-8e50-d125921c2e85)
3. **Festival crashes after 1-2 seconds**
4. When reopening Festival my music library is still empty.

## Crash report
If Festival is crashing, you may have a file here:

```
PanicInfo {
    payload: Any { .. },
    message: Some(
        range end index 4 out of range for slice of length 3,
    ),
    location: Location {
        file: "/home/runner/.cargo/registry/src/index.crates.io-6f17d22bba15001f/readable-0.8.9/src/date.rs",
        line: 783,
        col: 35,
    },
    can_unwind: true,
}

Thread {
    id: ThreadId(
        15,
    ),
    name: None,
    ..
}

info:
   OS      | linux x86_64
   args    | ArgsOs { inner: ["/usr/bin/festival"] }
   build   | Release
   commit  | 894a5f1b8dfa14b8b73157511c0d4baab6d06063
   threads | 12
   version | shukusai v0.0.1
   elapsed | 32.323123134 seconds

stack backtrace:
   0: <unknown>
   1: <unknown>
   2: <unknown>
   3: <unknown>
   4: <unknown>
   5: <unknown>
   6: <unknown>
   7: <unknown>
   8: <unknown>
   9: <unknown>
  10: <unknown>
  11: <unknown>
  12: <unknown>
  13: <unknown>
  14: <unknown>


```

**Comment by hinto-janai** [comment]
Should be fixed by https://github.com/hinto-janai/readable/pull/1.

Can you try [`v1.0.1`](https://github.com/hinto-janai/festival/releases) and see if it works?

**Comment by moritz1000** [comment]
> Can you try [`v1.0.1`](https://github.com/hinto-janai/festival/releases) and see if it works?

Thanks for your reply!

So the god news is that it does work now on folders that previously crashed the program!

___

The bad news that when I try to import 26,4 GB of music the program still crashes at the last step "100% Finalizing Collection" but does not create a crash report. I guess is a different issue now..?

**Comment by hinto-janai** [comment]
Can you try running from a console and post the output here with:
```bash
./festival --log-level debug
```

I'm suspecting an OOM kill. Unfortunately, Festival uses a ton of memory during a Collection reset. How much memory do you have?

**Comment by moritz1000** [comment]
> Can you try running from a console and post the output here with:
> 
> ```shell
> ./festival --log-level debug
> ```
> 
> I'm suspecting an OOM kill. Unfortunately, Festival uses a ton of memory during a Collection reset. How much memory do you have?

Unfortunately my terminal crashes alongside Festival (and my whole PC freezes for about 3 seconds) so I can't post any output. My PC has 16GB of RAM. 
You are probably right about the OOM kill. 

Should we close this issue since the original cause for the crash got fixed?

**Comment by hinto-janai** [comment]
I have a 257GB Collection that is able to be scanned, created, and saved with a restricted 1GB of memory:
```bash
systemd-run --scope -p MemoryMax=1G --user ./festival
```
so it probably isn't OOM, unless you are actively using most of that 16GB of RAM. The terminal crashing is weird as well, a program crashing shouldn't take down the shell it's running in, let alone the terminal. There's probably a different issue going on here.

> Should we close this issue since the original cause for the crash got fixed?

Sure.

**Comment by thesunnyk** [comment]
Hello. I'm still getting this issue. Date related

```
mass_panic!() - Saved panic log to: /home/kalsi/.local/share/festival/gui/txt/crash.txt                                 
                                                                                                                        
----- MASS PANIC: shukusai/src/panic.rs @ 52 -----                                                                      
PanicInfo {                                                                                                             
    payload: Any { .. },                                                                                                
    message: Some(                                                                                                      
        range end index 4 out of range for slice of length 1,                                                           
    ),                                                                                                                  
    location: Location {                                                                                                
        file: "/home/runner/.cargo/registry/src/index.crates.io-6f17d22bba15001f/readable-0.8.10/src/date.rs",          
        line: 785,                                                                                                      
        col: 35,                                            
    },                                                                                                                  
    can_unwind: true,                                                                                                   
}                                                                                                                       
                                                            
Thread {                                                                                                                
    id: ThreadId(                                           
        12,                                                                                                             
    ),                                                                                                                  
    name: None,                                             
    ..                                                                                                                  
}                                                                                                                       
                                                                                                                        
info:                                                                                                                   
   OS      | linux x86_64                                                                                               
   args    | ArgsOs { inner: ["Festival"] }                                                                             
   build   | Release                                                                                                    
   commit  | d2a0ddfd6e73d091f3b26b54bd6addb063f1a210   threads | 16                                                    
   version | shukusai v0.0.2                                                                                            
   elapsed | 1.508650971 seconds                                                                                        

stack backtrace:                                                                                                        
   0: shukusai::panic::set_panic_hook::{{closure}}                                                                      
   1: <alloc::boxed::Box<F,A> as core::ops::function::Fn<Args>>::call                                                   
             at /rustc/90c541806f23a127002de5b4038be731ba1458ca/library/alloc/src/boxed.rs:1987:9                       
   2: std::panicking::rust_panic_with_hook                                                                              
             at /rustc/90c541806f23a127002de5b4038be731ba1458ca/library/std/src/panicking.rs:695:13                     
   3: std::panicking::begin_panic_handler::{{closure}}                                                                  
             at /rustc/90c541806f23a127002de5b4038be731ba1458ca/library/std/src/panicking.rs:582:13                     
   4: std::sys_common::backtrace::__rust_end_short_backtrace                                                            
             at /rustc/90c541806f23a127002de5b4038be731ba1458ca/library/std/src/sys_common/backtrace.rs:150:18          
   5: rust_begin_unwind                                                                                                 
             at /rustc/90c541806f23a127002de5b4038be731ba1458ca/library/std/src/panicking.rs:578:5                      
   6: core::panicking::panic_fmt                                                                                        
             at /rustc/90c541806f23a127002de5b4038be731ba1458ca/library/core/src/panicking.rs:67:14
   7: core::slice::index::slice_end_index_len_fail_rt
             at /rustc/90c541806f23a127002de5b4038be731ba1458ca/library/core/src/slice/index.rs:78:5
   8: core::slice::index::slice_end_index_len_fail
             at /rustc/90c541806f23a127002de5b4038be731ba1458ca/library/core/src/slice/index.rs:70:9
   9: readable::date::Date::from_str_silent
  10: shukusai::ccd::the_loop::<impl shukusai::ccd::ccd::Ccd>::the_loop::{{closure}}::{{closure}}
  11: std::sys_common::backtrace::__rust_begin_short_backtrace
  12: core::ops::function::FnOnce::call_once{{vtable.shim}}
  13: <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once
             at /rustc/90c541806f23a127002de5b4038be731ba1458ca/library/alloc/src/boxed.rs:1973:9
  14: <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once
             at /rustc/90c541806f23a127002de5b4038be731ba1458ca/library/alloc/src/boxed.rs:1973:9
  15: std::sys::unix::thread::Thread::new::thread_start
             at /rustc/90c541806f23a127002de5b4038be731ba1458ca/library/std/src/sys/unix/thread.rs:108:17
  16: start_thread
             at ./nptl/./nptl/pthread_create.c:442:8
  17: __GI___clone3
             at ./misc/../sysdeps/unix/sysv/linux/x86_64/clone3.S:81
```

**Comment by hinto-janai** [comment]
Thanks for the report. After looking I found some more bugs.

Will hopefully be fixed next release.

**Comment by hinto-janai** [comment]
@thesunnyk Does the latest release [`v1.1.0`](https://github.com/hinto-janai/festival/releases/latest) fix this issue?

**Comment by thesunnyk** [comment]
Works for me now. Thanks a lot, love your work.
